# -*- coding: utf-8 -*-
"""Git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylBxkMzVo5d7Frocj0IsV1bR5MfSXJYr
"""

#Python lab For Analysis Visualiazation
import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()

# Simple referrals
G.add_edge("DRA", "DRB")
G.add_edge("DRA", "DRC")
G.add_edge("DRB", "DRC")
nx.draw(G, with_labels=True)
print("Centrality:")
print(nx.degree_centrality(G))
plt.show()